version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/finarg-frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "maven"
    directory: "/finarg-backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/finarg-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "docker"
    directory: "/finarg-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
